routes/web.php
<?php

/*
 * Authentication routes.
 */

 Auth::routes();

/*
 * Website routes.
 */

Route::get('/', 'HomeHandler')->name('home')->middleware('guest');

/*
 * Application routes.
 */

Route::prefix('app')->middleware('auth')->group(function () {
    Route::get('/', 'DashboardHandler')->name('dashboard');

    // Projects
    Route::get('/new', 'Projects\CreateProjectHandler')->name('projects.create');
    Route::post('/new', 'Projects\StoreProjectHandler')->name('projects.store');
    Route::get('/{project}', 'Projects\EditProjectHandler')->name('projects.edit');
    Route::put('/{project}', 'Projects\UpdateProjectHandler')->name('projects.update');
    Route::delete('/{project}', 'Projects\DeleteProjectHandler')->name('projects.delete');

    // Sections
    Route::post('/{project}/sections', 'Sections\StoreSectionHandler')->name('sections.store');
    Route::get('/{project}/sections/{section}', 'Sections\EditSectionHandler')->name('sections.edit');
    ROute::patch('/{project}/sections/{section}', 'Sections\UpdateSectionHandler')->name('sections.update');
});

app/Models/Section.php
<?php

namespace App\Models;

use App\Jobs\File\ReadFileCommand;
use App\Jobs\File\WriteFileCommand;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Bus;
use App\Models\Helpers\RoutesByHashid;
use Illuminate\Support\Str;
use Illuminate\Support\Collection;

/**
 * @property \Carbon\Carbon $deleted_at
 * @property mixed          $project
 * @property mixed          file
 * @property mixed          project_id
 */
class Section extends BaseModel
{
    use RoutesByHashid;

    protected $fillable = [
        'title',
        'status',
        'file_content',
        'project_id',
    ];

    /**
     * Override save method so we create the file for the section.
     *
     * @param array $options
     * @return bool
     */
    public function save(array $options = [])
    {
        if (is_null($this->file)) {
            $this->setAttribute('file_content', [
                'ops' => [],
            ]);
        }

        return parent::save($options);
    }

    /**
     * @return BelongsTo
     */
    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    /**
     * Fetch content of the section file.
     *
     * @return Collection
     */
    public function getFileContentAttribute(): Collection
    {
        if (is_null($this->attributes['file'])) {
            return [];
        }

        $data = Bus::dispatchNow(new ReadFileCommand($this->file));

        if (is_null($data)) {
            return collect([
                'ops' => [],
            ]);
        }

        return collect(json_decode($data, true));
    }

    /**
     * Set content of the section file.
     *
     * @param array $data
     */
    public function setFileContentAttribute(array $data)
    {
        if (is_null($this->file)) {
            $this->attributes['file'] = $this->project_id . '/' . uniqid('sect-') . '.json';
        }

        Bus::dispatchNow(new WriteFileCommand($this->file, json_encode($data)));
    }

    /**
     * Truncates the section's title.
     *
     * @return void
     */
    public function getSmallTitleAttribute()
    {
        return Str::limit($this->attributes['title'], 120, '...');
    }
}

resources/views/comps/content-editing.blade.php
<div class="max-w-2xl mx-auto flex justify-center">
    <aside class="flex-auto max-w-xs pr-8">
        <a href="{{ route('projects.edit', $project) }}" class="font-bold text-md text-black no-underline">{{ $project->name }}</a>
        @foreach ($project->sections as $section)
            <div class="pt-2">
                <a href="{{ route('sections.edit', [$project, $section]) }}" class="text-sm text-grey-dark no-underline {{ active('sections.edit', [$project, $section]) }}">
                    {{ $section->small_title }}
                </a>
            </div>
        @endforeach

        {{ html()->form('POST', route('sections.store', $project))->class('w-full mt-8 flex')->open() }}
            <div class="flex-grow field">
                {{ html()->text('title')->class('field__input')->required()->placeholder(__('Nova seção')) }}
                {{ form_field()->submit('+')->attributes(['style' => 'visibility:hidden']) }}
            </div>
        {{ html()->form()->close() }}
    </aside>
    <main class="flex-grow bg-white shadow-md rounded p-4">
        {{ $slot }}
    </main>
</div>

resources/views/comps/logout-button.blade.php
<a href="{{ route('logout') }}"
    class="no-underline hover:underline text-grey-darker text-sm"
    onclick="event.preventDefault();
    document.getElementById('logout-form').submit();">{{ __('Logout') }}</a>
<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
    {{ csrf_field() }}
</form>

resources/views/comps/section-title.blade.php
<h1 class="text-4xl font-light text-grey-dark mb-8">
    {{ $slot }}
</h1>